name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.x'
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y proj-bin libproj-dev
          pip install stactools open-science-catalog-builder/
      # Fix timestamps
      - name: restore timestamps
        uses: chetan/git-restore-mtime-action@v1
      - name: Build static Catalog
        run: |
          osc build ./ -o build/ \
            --root-href "https://constantinius.github.io/osc-demo/"
          stac copy build/collection.json dist -l https://constantinius.github.io/osc-demo -t ABSOLUTE_PUBLISHED
          cp build/{codelists.xml,eo-missions.json,metrics.json,themes.json,variables.json} dist/
      - name: Copying Catalog client
        run: |
          cp -r client/* dist/
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: dist
  # Deploy job
  # deploy:
  #   # Add a dependency to the build job
  #   needs: build

  #   # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
  #   permissions:
  #     pages: write      # to deploy to Pages
  #     id-token: write   # to verify the deployment originates from an appropriate source

  #   # Deploy to the github-pages environment
  #   environment:
  #     name: github-pages
  #     url: ${{ steps.deployment.outputs.page_url }}

  #   # Specify runner + deployment step
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Deploy to GitHub Pages
  #       id: deployment
  #       uses: actions/deploy-pages@v1
